import nnsight
import torch as t
from neuron_attribution import ST


def logit_diff(
    model: nnsight.LanguageModel,
    clean_idx: t.Tensor,
    patch_idx: t.Tensor | None = None,
) -> t.Tensor:
  logits = model.output.logits[:, -1, :]
  return t.gather(
      logits, dim=-1, index=patch_idx.view(-1, 1)
  ).squeeze(-1) - t.gather(
      logits, dim=-1, index=clean_idx.view(-1, 1)
  ).squeeze(-1)


def target_similarity(
    model: nnsight.LanguageModel,
    prompt_len: int,
    model_outputs: t.Tensor,
    target_embds: t.Tensor,
) -> t.Tensor:
  """
  Calculates the similarity between the target embeddings and the model's output.
  The target embeddings are generated by the full model on modified prompts.

  Args:
      model: The language model to use for generating responses
      target_embeddings: The target embeddings to compare the model's output to.
  """
  sentences = model.tokenizer.batch_decode(model_outputs[:, prompt_len:])

  return ST.similarity_pairwise(ST.encode(sentences), target_embds).to(model.device)


def eos_metric(
    model: nnsight.LanguageModel,
) -> t.Tensor:
  """Return the logits of the end of sequence token."""
  return -model.output.logits[:, -1, model.tokenizer.bos_token_id]
